import os


# Screen settings
SPRITE_SIZE = 16
SPRITE_SCALE = 4
IMAGE_SIZE = SPRITE_SIZE * SPRITE_SCALE

SCREEN_WIDTH = 16 * IMAGE_SIZE
SCREEN_HEIGHT = 14 * IMAGE_SIZE

# FPS settings
FPS = 60

# Colour definitions
DARK_GREY = (128, 128, 128)
BLACK = (0, 0, 0)
